INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (12, 'EMAIL', 'info@flirteros.de');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (15, 'EMAIL', 'bla@gmx.de');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (26, 'EMAIL', 'admin@gmail.com');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (105, 'EMAIL', 'gina.wild@web.de');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (115, 'EMAIL', 'bla@gmail.com');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (205, 'TELEFON', '07121333444');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (305, 'FAX', '07121333555');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (405, 'MOBILE', '01732345555');
INSERT INTO contactmethods (id, contactmethod, contactvalue) VALUES (505, 'INTERNET', 'http://www.flirteros.de');